Sound is restored across reboots
 * Restoring sound the first time we boot into UI
 * Simplified first_boot flag as it was mistakenly reset in the script

diff --git a/bin/kano-ui-autostart b/bin/kano-ui-autostart
--- a/bin/kano-ui-autostart
+++ b/bin/kano-ui-autostart
@@ -40,28 +40,30 @@ function track_startup
     fi
 }
 
-# Is this the first time we executed this boot?
-test -f /run/lock/desktop_init_run
-DESKTOP_RUN=$?
-touch /run/lock/desktop_init_run
-FIRST_BOOT=1
 
-if [ "$DESKTOP_RUN" -eq 1 ] ; then
+# Detect if we are running for the first time since boot
+boot_control_file=/var/run/lock/kano_ui_autostart_first_boot
+if [ -f $boot_control_file ]; then
+    FIRST_BOOT=0
+else
+    touch $boot_control_file
+    FIRST_BOOT=1
+fi
 
-   logger --id --tag "info" "kano-uixinit-systemd first execution"
+if [ "$FIRST_BOOT" -eq 1 ] ; then
 
-   # Finalise account setup
-   # NB sudo costs us 1 second here, could save it by checking the
-   # json file
-   sudo kano-init finalise || FIRST_BOOT=0
+    logger --id --tag "info" "kano-ui-autostart first execution, completing kano-init"
 
-   track_startup
+    # Finalise account setup
+    # NB sudo costs us 1 second here, could save it by checking the
+    # json file
+    sudo kano-init finalise
 
-   if [ "$FIRST_BOOT" -eq 1 ] ; then
-       # Finalise account setup
-       logger --id --tag "info" "kano-uixinit first boot"
-       sudo kano-updater first-boot
-   fi
+    track_startup
+
+    # Finalise account setup
+    logger --id --tag "info" "kano-ui-autostart running kano-updater first-boot"
+    sudo kano-updater first-boot
 
 fi
 
@@ -115,11 +117,31 @@ kill %?xrefresh
 
 # TODO: move me to a systemd unit service
 if [ "$FIRST_BOOT" -eq 1 ]; then
+
     # regenerating ssh keys
+    logger --id --tag "info" "kano-ui-autostart regenerating ssh host keys"
     if [ `getent group kanousers | wc -l` -eq 1 ]; then
         sudo regenerate-ssh-keys &
     fi
+
+    # Restore sound volume on boot
+    if [ -e /lib/systemd/system/alsa-restore.service ]; then
+	# Redirect both stderr and stdout to null, we can do our own logging
+	sudo systemctl start alsa-restore &> /dev/null
+	ret_val="$?"
+	if [ "$ret_val" -ne 0 ]; then
+	    touch /tmp/sound-failed
+            logger --id --tag "warn" "Failed to restore volume level, ret code: $ret_val"
+	else
+	    touch /tmp/sound-restored
+	    logger --id --tag "info" "Audio volume level was successfully restored"
+	fi
+    else
+	touch /tmp/sound-error
+	logger --id --tag "warn" "alsa-restore not found, cannott attempt to restore volume level"
+    fi
 fi
+
 
 # load compositor if the new driver is running
 (xdriinfo | grep vc4 ) && xcompmgr &
@@ -137,10 +159,10 @@ rm -rf  ~/Desktop
 # Except on Raspberry models below RPi2B, because Dashboard is not supported.
 # Switching between both modes goes through systemd units (no lightdm restart).
 if [ "$is_rpi2_or_above" == "True" ] ; then
-    logger --id --tag "info" "Starting systemd Dashboard mode"
+    logger --id --tag "info" "kano-ui-autostart Starting systemd Dashboard mode"
     systemctl --user start kano-dashboard.service
 else
-    logger --id --tag "info" "Starting systemd Desktop mode"
+    logger --id --tag "info" "kano-ui-autostart Starting systemd Desktop mode"
     systemctl --user start kano-desktop.service
 fi
 
