Fixes dpkg-divert errors when attempting to upgrade.

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -60,11 +60,19 @@ case "$1" in
         # Disable kdesk
         sudo sed -i 's/\@kdesk/\@pcmanfm --desktop --profile LXDE/g' $LXDE_AUTOSTART
 
-        dpkg-divert --package kano-desktop --remove --rename \
-                    --divert /etc/xdg/menus/lxde-applications.menu.orig /etc/xdg/menus/lxde-applications.menu
+        # Remove Wolfram config file in sudoers
+        rm /etc/sudoers.d/wolfram-installer_conf
+        # Remove LibreOffice config file in sudoers
+        rm /etc/sudoers.d/libreoffice-installer_conf
 
         ;;
 esac
+
+
+if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ] || ( [ abort-upgrade = "$1" ] && dpkg --compare-versions "$2" lt 1.0-61.20140508 ); then
+    dpkg-divert --package kano-desktop --remove --rename \
+                --divert /etc/xdg/menus/lxde-applications.menu.orig /etc/xdg/menus/lxde-applications.menu
+fi
 
 #DEBHELPER#
 
